// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrTiH-W9BUCVKFRdvOTWDLNvUUVpjlb2I',
    appId: '1:459093801872:web:c7fc7d60824f58c1505115',
    messagingSenderId: '459093801872',
    projectId: 'ethos24-91898',
    authDomain: 'ethos24-91898.firebaseapp.com',
    storageBucket: 'ethos24-91898.appspot.com',
    measurementId: 'G-TK12RK7S67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfs3T_85LKytakfeFJ5oriH3lnYgV7CZ4',
    appId: '1:459093801872:android:51db6be44b8768a3505115',
    messagingSenderId: '459093801872',
    projectId: 'ethos24-91898',
    storageBucket: 'ethos24-91898.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgrAg1mOGBYe5Yr48eBfK1IYoIXEcESqA',
    appId: '1:459093801872:ios:310cf3e7f19a1eda505115',
    messagingSenderId: '459093801872',
    projectId: 'ethos24-91898',
    storageBucket: 'ethos24-91898.appspot.com',
    androidClientId: '459093801872-sei4b4c3rm62r15fh0g1q49urpe7durl.apps.googleusercontent.com',
    iosClientId: '459093801872-5eb2lraajsce6ik73ni60o3isvcp0kak.apps.googleusercontent.com',
    iosBundleId: 'com.example.baatcheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgrAg1mOGBYe5Yr48eBfK1IYoIXEcESqA',
    appId: '1:459093801872:ios:310cf3e7f19a1eda505115',
    messagingSenderId: '459093801872',
    projectId: 'ethos24-91898',
    storageBucket: 'ethos24-91898.appspot.com',
    androidClientId: '459093801872-sei4b4c3rm62r15fh0g1q49urpe7durl.apps.googleusercontent.com',
    iosClientId: '459093801872-5eb2lraajsce6ik73ni60o3isvcp0kak.apps.googleusercontent.com',
    iosBundleId: 'com.example.baatcheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrTiH-W9BUCVKFRdvOTWDLNvUUVpjlb2I',
    appId: '1:459093801872:web:0a31ea8d75e5bb7b505115',
    messagingSenderId: '459093801872',
    projectId: 'ethos24-91898',
    authDomain: 'ethos24-91898.firebaseapp.com',
    storageBucket: 'ethos24-91898.appspot.com',
    measurementId: 'G-RE2J6XS15S',
  );

}